CREATE TABLE IF NOT EXISTS taxi_signs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sign_description VARCHAR(255) NOT NULL
    );

CREATE TABLE IF NOT EXISTS taxi_ranks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_name VARCHAR(255) NOT NULL,
    location_address VARCHAR(255) NOT NULL
    );

CREATE TABLE IF NOT EXISTS taxi_routes (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   from_location VARCHAR(255) NOT NULL,
    to_location VARCHAR(255) NOT NULL,
    fare DECIMAL(10,2) NOT NULL,
    taxi_sign_id INT,
    from_location_rank_id INT,
    to_location_rank_id INT,

    FOREIGN KEY (taxi_sign_id) REFERENCES taxi_signs(id),
    FOREIGN KEY (from_location_rank_id) REFERENCES taxi_ranks(id),
    FOREIGN KEY (to_location_rank_id) REFERENCES taxi_ranks(id)
    );

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
    );